export const COUNTRIES = [
  { code: "+52", name: "México", flag: "🇲🇽" },
  { code: "+1", name: "USA", flag: "🇺🇸" },
  { code: "+34", name: "España", flag: "🇪🇸" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+57", name: "Colombia", flag: "🇨🇴" },
  { code: "+56", name: "Chile", flag: "🇨🇱" },
  { code: "+51", name: "Perú", flag: "🇵🇪" },
  { code: "+58", name: "Venezuela", flag: "🇻🇪" },
  { code: "+593", name: "Ecuador", flag: "🇪🇨" },
  { code: "+591", name: "Bolivia", flag: "🇧🇴" },
  { code: "+595", name: "Paraguay", flag: "🇵🇾" },
  { code: "+598", name: "Uruguay", flag: "🇺🇾" },
  { code: "+506", name: "Costa Rica", flag: "🇨🇷" },
  { code: "+507", name: "Panamá", flag: "🇵🇦" },
  { code: "+44", name: "UK", flag: "🇬🇧" },
  { code: "+33", name: "France", flag: "🇫🇷" },
  { code: "+49", name: "Germany", flag: "🇩🇪" },
  { code: "+55", name: "Brasil", flag: "🇧🇷" },
];

export const STRINGS = {
  es: {
    appName: "SignBridge",
    tagline: "Traducción bidireccional de lengua de señas",
    phone: "Número de teléfono",
    sendCode: "Enviar código",
    enterOtp: "Ingresa el código de 6 dígitos",
    otpSentTo: "Código enviado a",
    verify: "Verificar",
    resend: "Reenviar",
    resendIn: "Reenviar en",
    yourName: "Tu nombre",
    profilePhoto: "Foto de perfil",
    preferredLanguage: "Idioma preferido",
    continue: "Continuar",
    permissions: "Permisos",
    permCamera: "Cámara",
    permCameraDesc: "Para grabar tus señas",
    permMic: "Micrófono",
    permMicDesc: "Para traducir tu voz",
    permContacts: "Contactos",
    permContactsDesc: "Para compartir traducciones",
    grantAccess: "Conceder acceso",
    skipForNow: "Omitir por ahora",
    translator: "Traductor",
    dictionary: "Diccionario",
    profile: "Perfil",
    startSigning: "Presiona para grabar señas",
    recording: "Grabando...",
    stopAndSend: "Detener y enviar",
    typeMessage: "Escribe un mensaje...",
    recordVoice: "Grabar voz",
    send: "Enviar",
    searchSigns: "Buscar señas...",
    all: "Todo",
    letters: "Letras",
    words: "Palabras",
    logout: "Cerrar sesión",
    editProfile: "Editar perfil",
    language: "Idioma",
    settings: "Ajustes",
    save: "Guardar",
    tapToSign: "Toca para ver la seña",
    signAvatar: "Avatar de señas",
    clearChat: "Limpiar chat",
    favorites: "Frases favoritas",
    saveFavorite: "Guardar frase",
    savedFavorite: "Frase guardada",
    noFavorites: "Toca ⭐ en un mensaje para guardarlo aquí",
    deleteFavorite: "Eliminar frase",
    exportPdf: "Exportar PDF",
    exportTitle: "Historial de conversación",
    exportEmpty: "No hay mensajes para exportar",
    learn: "Aprender",
    dailyLesson: "Lección del día",
    lessonDesc: "5 señas nuevas cada día. Mantén tu racha.",
    startLesson: "Comenzar lección",
    practiceAgain: "Practicar de nuevo",
    lessonDone: "¡Lección de hoy completada!",
    comeBackTomorrow: "Vuelve mañana para continuar tu racha.",
    streak: "Racha",
    days: "días",
    bestStreak: "Mejor racha",
    learned: "Señas aprendidas",
    lessons: "Lecciones",
    whichSign: "¿Qué seña es esta?",
    question: "Pregunta",
    correct: "¡Correcto!",
    incorrect: "Incorrecto. Era:",
    next: "Siguiente",
    seeResults: "Ver resultados",
    yourScore: "Tu puntaje",
    finish: "Terminar",
    streakUp: "¡Racha aumentada!",
    shareWithContact: "Enviar a un contacto",
    sendTo: "Enviar a",
    change: "Cambiar",
    searchContacts: "Buscar contactos...",
    noContacts: "No hay contactos con número de teléfono",
    orTypeNumber: "O escribe un número",
    contactsWhy: "Elige a quién enviar el mensaje traducido. Tus contactos no salen de tu dispositivo.",
    contactsBlocked: "El acceso a contactos está bloqueado. Actívalo en Ajustes o escribe un número.",
    openSettings: "Abrir Ajustes",
    shareMessage: "Enviar mensaje",
    reviewMode: "Modo Repaso",
    reviewDesc: "Practica solo las señas que fallaste.",
    reviewEmpty: "Sin señas pendientes. ¡Vas muy bien!",
    weakSigns: "señas por repasar",
    startReview: "Repasar",
    mastered: "Señas dominadas",
    stillWeak: "Aún por repasar",
  },
  en: {
    appName: "SignBridge",
    tagline: "Bidirectional sign language translation",
    phone: "Phone number",
    sendCode: "Send code",
    enterOtp: "Enter 6-digit code",
    otpSentTo: "Code sent to",
    verify: "Verify",
    resend: "Resend",
    resendIn: "Resend in",
    yourName: "Your name",
    profilePhoto: "Profile photo",
    preferredLanguage: "Preferred language",
    continue: "Continue",
    permissions: "Permissions",
    permCamera: "Camera",
    permCameraDesc: "To record your signs",
    permMic: "Microphone",
    permMicDesc: "To translate your voice",
    permContacts: "Contacts",
    permContactsDesc: "To share translations",
    grantAccess: "Grant access",
    skipForNow: "Skip for now",
    translator: "Translator",
    dictionary: "Dictionary",
    profile: "Profile",
    startSigning: "Press to record signs",
    recording: "Recording...",
    stopAndSend: "Stop & send",
    typeMessage: "Type a message...",
    recordVoice: "Record voice",
    send: "Send",
    searchSigns: "Search signs...",
    all: "All",
    letters: "Letters",
    words: "Words",
    logout: "Log out",
    editProfile: "Edit profile",
    language: "Language",
    settings: "Settings",
    save: "Save",
    tapToSign: "Tap to see sign",
    signAvatar: "Sign avatar",
    clearChat: "Clear chat",
    favorites: "Favorite phrases",
    saveFavorite: "Save phrase",
    savedFavorite: "Phrase saved",
    noFavorites: "Tap ⭐ on a message to save it here",
    deleteFavorite: "Delete phrase",
    exportPdf: "Export PDF",
    exportTitle: "Conversation history",
    exportEmpty: "No messages to export",
    learn: "Learn",
    dailyLesson: "Daily lesson",
    lessonDesc: "5 new signs every day. Keep your streak.",
    startLesson: "Start lesson",
    practiceAgain: "Practice again",
    lessonDone: "Today's lesson completed!",
    comeBackTomorrow: "Come back tomorrow to continue your streak.",
    streak: "Streak",
    days: "days",
    bestStreak: "Best streak",
    learned: "Signs learned",
    lessons: "Lessons",
    whichSign: "Which sign is this?",
    question: "Question",
    correct: "Correct!",
    incorrect: "Incorrect. It was:",
    next: "Next",
    seeResults: "See results",
    yourScore: "Your score",
    finish: "Finish",
    streakUp: "Streak increased!",
    shareWithContact: "Send to a contact",
    sendTo: "Send to",
    change: "Change",
    searchContacts: "Search contacts...",
    noContacts: "No contacts with a phone number",
    orTypeNumber: "Or type a number",
    contactsWhy: "Pick who receives the translated message. Your contacts never leave your device.",
    contactsBlocked: "Contacts access is blocked. Enable it in Settings or type a number.",
    openSettings: "Open Settings",
    shareMessage: "Send message",
    reviewMode: "Review Mode",
    reviewDesc: "Practice only the signs you got wrong.",
    reviewEmpty: "No signs to review. You're doing great!",
    weakSigns: "signs to review",
    startReview: "Review",
    mastered: "Signs mastered",
    stillWeak: "Still to review",
  },
};

export type Lang = "es" | "en";
