export const COUNTRIES = [
  { code: "+52", name: "México", flag: "🇲🇽" },
  { code: "+1", name: "USA", flag: "🇺🇸" },
  { code: "+34", name: "España", flag: "🇪🇸" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+57", name: "Colombia", flag: "🇨🇴" },
  { code: "+56", name: "Chile", flag: "🇨🇱" },
  { code: "+51", name: "Perú", flag: "🇵🇪" },
  { code: "+58", name: "Venezuela", flag: "🇻🇪" },
  { code: "+593", name: "Ecuador", flag: "🇪🇨" },
  { code: "+591", name: "Bolivia", flag: "🇧🇴" },
  { code: "+595", name: "Paraguay", flag: "🇵🇾" },
  { code: "+598", name: "Uruguay", flag: "🇺🇾" },
  { code: "+506", name: "Costa Rica", flag: "🇨🇷" },
  { code: "+507", name: "Panamá", flag: "🇵🇦" },
  { code: "+44", name: "UK", flag: "🇬🇧" },
  { code: "+33", name: "France", flag: "🇫🇷" },
  { code: "+49", name: "Germany", flag: "🇩🇪" },
  { code: "+55", name: "Brasil", flag: "🇧🇷" },
];

export const STRINGS = {
  es: {
    appName: "SignBridge",
    tagline: "Traducción bidireccional de lengua de señas",
    phone: "Número de teléfono",
    sendCode: "Enviar código",
    enterOtp: "Ingresa el código de 6 dígitos",
    otpSentTo: "Código enviado a",
    verify: "Verificar",
    resend: "Reenviar",
    resendIn: "Reenviar en",
    yourName: "Tu nombre",
    profilePhoto: "Foto de perfil",
    preferredLanguage: "Idioma preferido",
    continue: "Continuar",
    permissions: "Permisos",
    permCamera: "Cámara",
    permCameraDesc: "Para grabar tus señas",
    permMic: "Micrófono",
    permMicDesc: "Para traducir tu voz",
    permContacts: "Contactos",
    permContactsDesc: "Para compartir traducciones",
    grantAccess: "Conceder acceso",
    skipForNow: "Omitir por ahora",
    translator: "Traductor",
    dictionary: "Diccionario",
    profile: "Perfil",
    startSigning: "Presiona para grabar señas",
    recording: "Grabando...",
    stopAndSend: "Detener y enviar",
    typeMessage: "Escribe un mensaje...",
    recordVoice: "Grabar voz",
    send: "Enviar",
    searchSigns: "Buscar señas...",
    all: "Todo",
    letters: "Letras",
    words: "Palabras",
    logout: "Cerrar sesión",
    editProfile: "Editar perfil",
    language: "Idioma",
    settings: "Ajustes",
    save: "Guardar",
    tapToSign: "Toca para ver la seña",
    signAvatar: "Avatar de señas",
    clearChat: "Limpiar chat",
    favorites: "Frases favoritas",
    saveFavorite: "Guardar frase",
    savedFavorite: "Frase guardada",
    noFavorites: "Toca ⭐ en un mensaje para guardarlo aquí",
    deleteFavorite: "Eliminar frase",
    exportPdf: "Exportar PDF",
    exportTitle: "Historial de conversación",
    exportEmpty: "No hay mensajes para exportar",
    learn: "Aprender",
    dailyLesson: "Lección del día",
    lessonDesc: "5 señas nuevas cada día. Mantén tu racha.",
    startLesson: "Comenzar lección",
    practiceAgain: "Practicar de nuevo",
    lessonDone: "¡Lección de hoy completada!",
    comeBackTomorrow: "Vuelve mañana para continuar tu racha.",
    streak: "Racha",
    days: "días",
    bestStreak: "Mejor racha",
    learned: "Señas aprendidas",
    lessons: "Lecciones",
    whichSign: "¿Qué seña es esta?",
    translatePhrase: "¿Cómo se dice esta frase?",
    phraseQuestion: "Frase completa",
    listen: "Escuchar",
    detecting: "Detectando seña...",
    detected: "Seña detectada",
    noSignDetected: "No se detectó ninguna seña, inténtalo de nuevo",
    recognitionError: "Error de reconocimiento. Revisa tu conexión.",
    tapToStop: "Toca para detener",
    tapToRecord: "Toca para grabar señas",
    avatarGallery: "Avatar de señas",
    avatarDesc: "Elige quién presenta tus traducciones en video",
    male: "Masculino",
    female: "Femenino",
    renderingAvatar: "Generando video del avatar...",
    tapChipToRemove: "Toca una seña para quitarla",
    syncedContacts: "Contactos sincronizados",
    contactSynced: "Contacto sincronizado automáticamente",
    contactAlreadySynced: "Contacto ya sincronizado",
    simulateProfileView: "Simular vista de perfil",
    lastSync: "Última sincronización",
    savedLocally: "Guardado localmente",
    noSyncedContacts: "Aún no hay contactos sincronizados. Se guardan automáticamente al abrir un perfil por primera vez.",
    question: "Pregunta",
    correct: "¡Correcto!",
    incorrect: "Incorrecto. Era:",
    next: "Siguiente",
    seeResults: "Ver resultados",
    yourScore: "Tu puntaje",
    finish: "Terminar",
    streakUp: "¡Racha aumentada!",
    shareWithContact: "Enviar a un contacto",
    sendTo: "Enviar a",
    change: "Cambiar",
    searchContacts: "Buscar contactos...",
    noContacts: "No hay contactos con número de teléfono",
    orTypeNumber: "O escribe un número",
    contactsWhy: "Elige a quién enviar el mensaje traducido. Tus contactos no salen de tu dispositivo.",
    contactsBlocked: "El acceso a contactos está bloqueado. Actívalo en Ajustes o escribe un número.",
    openSettings: "Abrir Ajustes",
    shareMessage: "Enviar mensaje",
    reviewMode: "Modo Repaso",
    reviewDesc: "Practica solo las señas que fallaste.",
    reviewEmpty: "Sin señas pendientes. ¡Vas muy bien!",
    weakSigns: "señas por repasar",
    startReview: "Repasar",
    mastered: "Señas dominadas",
    stillWeak: "Aún por repasar",
    phrases: "Frases",
    phrasesTitle: "Frases completas",
    searchPhrases: "Buscar frase...",
    achievements: "Logros y medallas",
    newBadge: "¡Nueva medalla!",
    locked: "Bloqueado",
    unlockedOn: "Desbloqueado",
    shareWhatsApp: "Compartir en WhatsApp",
    shareImage: "Compartir imagen",
    shareBadgeText: "¡Desbloqueé una medalla en SignBridge!",
    streakLabel: "Racha",
    signsMastered: "Señas dominadas",
    manageFavorites: "Gestionar frases favoritas",
    rename: "Renombrar",
    delete: "Eliminar",
    confirmDelete: "¿Eliminar esta frase?",
    yes: "Sí",
    no: "No",
    moveUp: "Subir",
    moveDown: "Bajar",
    noFavoritesYet: "Aún no tienes frases favoritas. Guarda una desde el traductor con ⭐.",
    cancel: "Cancelar",
    streakPending: "Tu lección de hoy está pendiente",
    streakKeep: "No pierdas tu racha de",
    streakStart: "Empieza tu racha hoy con 5 señas nuevas",
    goToLesson: "Ir a la lección",
    chats: "Chats",
    newChat: "Nuevo chat",
    noChats: "Aún no tienes conversaciones",
    noChatsDesc: "Empieza un chat con un contacto que ya use SignBridge. Podrán escribirse, hablar o hacer señas.",
    onSignBridge: "En SignBridge",
    searchingContacts: "Buscando contactos en SignBridge...",
    noMatchedContacts: "Ninguno de tus contactos usa SignBridge todavía. Escribe un número para intentarlo.",
    contactsForChat: "Encuentra a quién de tus contactos ya usa SignBridge. Tus contactos no salen de tu dispositivo.",
    notRegistered: "Este número aún no está registrado en SignBridge",
    showAsSign: "Ver en señas",
    hideSign: "Ocultar señas",
    listenMsg: "Escuchar",
    sendSigns: "Enviar señas",
    holdToRecord: "Mantén presionado el micrófono para grabar",
    you: "Tú",
    voiceMessage: "Nota de voz",
    signMessage: "Señas",
    textMessage: "Texto",
    chatEmpty: "Envía tu primer mensaje: texto, voz o señas.",
    cameraBlocked: "El acceso a la cámara está bloqueado. Actívalo en Ajustes.",
    signComposeTitle: "Mensaje en señas",
    sendingVoice: "Transcribiendo nota de voz...",
    sending: "Enviando...",
    premium: "SignBridge Premium",
    premiumTitle: "Desbloquea SignBridge Premium",
    premiumSubtitle: "Sin anuncios, todos los avatares y mensajes más largos.",
    benefitNoAds: "Sin anuncios ni interrupciones",
    benefitAvatars: "Acceso a todos los avatares masculinos y femeninos",
    benefitPriority: "Traducción prioritaria y mensajes más largos (hasta 60 s)",
    planMonthly: "Mensual",
    planYearly: "Anual",
    perMonth: "al mes",
    perYear: "al año",
    bestValue: "Mejor valor",
    freeTrial: "7 días de prueba gratis",
    startTrial: "Iniciar prueba gratis de 7 días",
    subscribeNow: "Suscribirme ahora",
    terms: "Términos de servicio",
    privacy: "Política de privacidad",
    restorePurchases: "Restaurar compras",
    nothingToRestore: "No hay compras para restaurar. Disponible en la versión de tiendas.",
    storeOnly: "Las compras se completan en la versión publicada en Google Play / App Store. Mientras tanto puedes activar el Modo prueba.",
    testMode: "Modo prueba",
    activateTest: "Activar Premium sin pagar (prueba)",
    deactivateTest: "Desactivar Premium (prueba)",
    premiumActive: "¡Ya eres Premium!",
    premiumActiveDesc: "Disfruta de todos los avatares, sin anuncios y mensajes de señas de hasta 60 segundos.",
    premiumActivated: "Premium activado",
    currentPlan: "Plan actual",
    freePlan: "Plan gratuito",
    upgrade: "Mejorar a Premium",
    premiumOnly: "Exclusivo Premium",
    lockedAvatar: "Este avatar es exclusivo de SignBridge Premium",
    limitReached: "Límite de grabación alcanzado",
    limitReachedDesc: "El plan gratuito permite mensajes de señas de hasta 15 segundos. Con Premium grabas hasta 60 segundos.",
    reasonAvatar: "Elige libremente entre todos los avatares con Premium.",
    reasonAds: "Con Premium desaparece toda la publicidad.",
    adTitle: "Anuncio",
    adPlaceholder: "Espacio publicitario (AdMob se conectará en la versión publicada)",
    adSkipIn: "Cerrar en",
    adClose: "Cerrar anuncio",
    removeAds: "Quitar anuncios con Premium",
    comingSoon: "Disponible próximamente",
    processing: "Procesando...",
    sessionExpired: "Tu sesión expiró. Inicia sesión de nuevo.",
    signSpeed: "Velocidad de las señas",
    signSpeedDesc: "Aplica a todos los videos del avatar. Lenta es ideal para aprender.",
    speedSlow: "Lenta",
    speedNormal: "Normal",
    speedFast: "Rápida",
    switchCamera: "Cambiar cámara",
    analyzingCarefully: "Analizando señas cuidadosamente...",
    recordingVideoHint: "Grabando video · al detener se analizará la secuencia completa",
    reviewSigns: "Señas detectadas",
    translateSigns: "Traducir",
    realInterpreter: "Intérprete real",
    realInterpreterDesc: "Las palabras con clip disponible se muestran con un intérprete real; el resto con tu avatar 2D.",
    clipsAvailable: "señas en video",
  },
  en: {
    appName: "SignBridge",
    tagline: "Bidirectional sign language translation",
    phone: "Phone number",
    sendCode: "Send code",
    enterOtp: "Enter 6-digit code",
    otpSentTo: "Code sent to",
    verify: "Verify",
    resend: "Resend",
    resendIn: "Resend in",
    yourName: "Your name",
    profilePhoto: "Profile photo",
    preferredLanguage: "Preferred language",
    continue: "Continue",
    permissions: "Permissions",
    permCamera: "Camera",
    permCameraDesc: "To record your signs",
    permMic: "Microphone",
    permMicDesc: "To translate your voice",
    permContacts: "Contacts",
    permContactsDesc: "To share translations",
    grantAccess: "Grant access",
    skipForNow: "Skip for now",
    translator: "Translator",
    dictionary: "Dictionary",
    profile: "Profile",
    startSigning: "Press to record signs",
    recording: "Recording...",
    stopAndSend: "Stop & send",
    typeMessage: "Type a message...",
    recordVoice: "Record voice",
    send: "Send",
    searchSigns: "Search signs...",
    all: "All",
    letters: "Letters",
    words: "Words",
    logout: "Log out",
    editProfile: "Edit profile",
    language: "Language",
    settings: "Settings",
    save: "Save",
    tapToSign: "Tap to see sign",
    signAvatar: "Sign avatar",
    clearChat: "Clear chat",
    favorites: "Favorite phrases",
    saveFavorite: "Save phrase",
    savedFavorite: "Phrase saved",
    noFavorites: "Tap ⭐ on a message to save it here",
    deleteFavorite: "Delete phrase",
    exportPdf: "Export PDF",
    exportTitle: "Conversation history",
    exportEmpty: "No messages to export",
    learn: "Learn",
    dailyLesson: "Daily lesson",
    lessonDesc: "5 new signs every day. Keep your streak.",
    startLesson: "Start lesson",
    practiceAgain: "Practice again",
    lessonDone: "Today's lesson completed!",
    comeBackTomorrow: "Come back tomorrow to continue your streak.",
    streak: "Streak",
    days: "days",
    bestStreak: "Best streak",
    learned: "Signs learned",
    lessons: "Lessons",
    whichSign: "Which sign is this?",
    translatePhrase: "How do you say this phrase?",
    phraseQuestion: "Full phrase",
    listen: "Listen",
    detecting: "Detecting sign...",
    detected: "Sign detected",
    noSignDetected: "No sign detected, please try again",
    recognitionError: "Recognition error. Check your connection.",
    tapToStop: "Tap to stop",
    tapToRecord: "Tap to record signs",
    avatarGallery: "Sign avatar",
    avatarDesc: "Choose who presents your video translations",
    male: "Male",
    female: "Female",
    renderingAvatar: "Rendering avatar video...",
    tapChipToRemove: "Tap a sign to remove it",
    syncedContacts: "Synced contacts",
    contactSynced: "Contacto sincronizado automáticamente",
    contactAlreadySynced: "Contact already synced",
    simulateProfileView: "Simulate profile view",
    lastSync: "Last sync",
    savedLocally: "Saved locally",
    noSyncedContacts: "No synced contacts yet. They are saved automatically the first time you open a profile.",
    question: "Question",
    correct: "Correct!",
    incorrect: "Incorrect. It was:",
    next: "Next",
    seeResults: "See results",
    yourScore: "Your score",
    finish: "Finish",
    streakUp: "Streak increased!",
    shareWithContact: "Send to a contact",
    sendTo: "Send to",
    change: "Change",
    searchContacts: "Search contacts...",
    noContacts: "No contacts with a phone number",
    orTypeNumber: "Or type a number",
    contactsWhy: "Pick who receives the translated message. Your contacts never leave your device.",
    contactsBlocked: "Contacts access is blocked. Enable it in Settings or type a number.",
    openSettings: "Open Settings",
    shareMessage: "Send message",
    reviewMode: "Review Mode",
    reviewDesc: "Practice only the signs you got wrong.",
    reviewEmpty: "No signs to review. You're doing great!",
    weakSigns: "signs to review",
    startReview: "Review",
    mastered: "Signs mastered",
    stillWeak: "Still to review",
    phrases: "Phrases",
    phrasesTitle: "Full phrases",
    searchPhrases: "Search phrase...",
    achievements: "Achievements & badges",
    newBadge: "New badge!",
    locked: "Locked",
    unlockedOn: "Unlocked",
    shareWhatsApp: "Share on WhatsApp",
    shareImage: "Share image",
    shareBadgeText: "I unlocked a badge in SignBridge!",
    streakLabel: "Streak",
    signsMastered: "Signs mastered",
    manageFavorites: "Manage favorite phrases",
    rename: "Rename",
    delete: "Delete",
    confirmDelete: "Delete this phrase?",
    yes: "Yes",
    no: "No",
    moveUp: "Move up",
    moveDown: "Move down",
    noFavoritesYet: "No favorite phrases yet. Save one from the translator with ⭐.",
    cancel: "Cancel",
    streakPending: "Today's lesson is pending",
    streakKeep: "Don't lose your streak of",
    streakStart: "Start your streak today with 5 new signs",
    goToLesson: "Go to lesson",
    chats: "Chats",
    newChat: "New chat",
    noChats: "No conversations yet",
    noChatsDesc: "Start a chat with a contact who already uses SignBridge. You can type, talk or sign.",
    onSignBridge: "On SignBridge",
    searchingContacts: "Looking for contacts on SignBridge...",
    noMatchedContacts: "None of your contacts use SignBridge yet. Type a number to try.",
    contactsForChat: "Find which of your contacts already use SignBridge. Your contacts never leave your device.",
    notRegistered: "This number is not registered on SignBridge yet",
    showAsSign: "Show in signs",
    hideSign: "Hide signs",
    listenMsg: "Listen",
    sendSigns: "Send signs",
    holdToRecord: "Hold the microphone to record",
    you: "You",
    voiceMessage: "Voice note",
    signMessage: "Signs",
    textMessage: "Text",
    chatEmpty: "Send your first message: text, voice or signs.",
    cameraBlocked: "Camera access is blocked. Enable it in Settings.",
    signComposeTitle: "Sign message",
    sendingVoice: "Transcribing voice note...",
    sending: "Sending...",
    premium: "SignBridge Premium",
    premiumTitle: "Unlock SignBridge Premium",
    premiumSubtitle: "No ads, every avatar and longer messages.",
    benefitNoAds: "No ads or interruptions",
    benefitAvatars: "Access to all male and female avatars",
    benefitPriority: "Priority translation and longer messages (up to 60 s)",
    planMonthly: "Monthly",
    planYearly: "Yearly",
    perMonth: "per month",
    perYear: "per year",
    bestValue: "Best value",
    freeTrial: "7-day free trial",
    startTrial: "Start 7-day free trial",
    subscribeNow: "Subscribe now",
    terms: "Terms of service",
    privacy: "Privacy policy",
    restorePurchases: "Restore purchases",
    nothingToRestore: "No purchases to restore. Available in the store version.",
    storeOnly: "Purchases are completed in the published Google Play / App Store version. Meanwhile you can enable Test mode.",
    testMode: "Test mode",
    activateTest: "Activate Premium without paying (test)",
    deactivateTest: "Deactivate Premium (test)",
    premiumActive: "You're Premium!",
    premiumActiveDesc: "Enjoy every avatar, no ads and sign messages up to 60 seconds.",
    premiumActivated: "Premium activated",
    currentPlan: "Current plan",
    freePlan: "Free plan",
    upgrade: "Upgrade to Premium",
    premiumOnly: "Premium only",
    lockedAvatar: "This avatar is exclusive to SignBridge Premium",
    limitReached: "Recording limit reached",
    limitReachedDesc: "The free plan allows sign messages up to 15 seconds. With Premium you can record up to 60 seconds.",
    reasonAvatar: "Choose freely among all avatars with Premium.",
    reasonAds: "Premium removes all advertising.",
    adTitle: "Advertisement",
    adPlaceholder: "Ad placeholder (AdMob will be connected in the published version)",
    adSkipIn: "Close in",
    adClose: "Close ad",
    removeAds: "Remove ads with Premium",
    comingSoon: "Coming soon",
    processing: "Processing...",
    sessionExpired: "Your session expired. Please sign in again.",
    signSpeed: "Sign speed",
    signSpeedDesc: "Applies to every avatar video. Slow is great for learning.",
    speedSlow: "Slow",
    speedNormal: "Normal",
    speedFast: "Fast",
    switchCamera: "Switch camera",
    analyzingCarefully: "Carefully analyzing signs...",
    recordingVideoHint: "Recording video · the full sequence is analyzed when you stop",
    reviewSigns: "Detected signs",
    translateSigns: "Translate",
    realInterpreter: "Real interpreter",
    realInterpreterDesc: "Words with an available clip are shown by a real interpreter; the rest by your 2D avatar.",
    clipsAvailable: "video signs",
  },
};

export type Lang = "es" | "en";
